### ISSUE TITLE
Remove crypto from utils

### ISSUE THREAD

**Issue by jteheran** [opensciencegrid/osg-pki-tools#46]
Move the Csr class and get_ssl_context to request.py and get rid of the BuildRequires

**Comment by DrDaveD** [comment]
Also move the code specific to the osg-cert-request command line tool out of request.py to a new file, maybe cert-request.py.   I would prefer then that what's left in request.py to be named something more descriptive, like csr.py or cert-utils.py.

An alternative way to look at the whole issue is to move the common cert-related code between the two tools into a new file, such as cert-utils.py, and to rename request.py to cert-request.py.
